### ISSUE TITLE
Do nothing by default

### ISSUE THREAD

**Issue by mvz** [capistrano/stats#30]
I was just trying to deploy my application, and instead of the smooth automated experience I was expecting it started asking me loads of slightly obscure[1] questions about statistics. It would be much more user-friendly if instead it would:
- Send nothing by default
- Nag the user with a message including an URL for more information until statistics were configured either way.

[1] By obscure I mean I had to google the questions to find the needed information. In fact, I still don't know how to decide whether to 'disable the UDP ping to the metrics server'.

**Comment by leehambley** [comment]
Please feel free to submit a PR with tour proposed changes. We have enough
work with Capistrano itself, and the exact nature of messages, prompts,
expected default behaviour /etc has already cost plenty of our time, and
the time of contributors who have done their best to build something that
makes sense.

**Comment by mvz** [comment]
Fair enough. As I too have enough work with other projects and don't have time to investigate what exactly this stats thing is doing, I have downgraded dependency on the capistrano gem to '3.2.1' for the time being.

I may submit a PR when I find the time.

**Comment by guigs** [comment]
+1

**Comment by mvz** [comment]
Closing this as the stats dependency was removed in https://github.com/capistrano/capistrano/commit/251e39c19364be508efee634cc4b1da214253c67

**Comment by leehambley** [comment]
Cool, cheers

**Comment by jspooner** [comment]
+1

**Comment by leehambley** [comment]
What's the +1 for?

**Comment by mvz** [comment]
@jspooner stats were removed from capistrano in 3.4. If they bother you (like they bothered me), you should probably upgrade to that version.
