### ISSUE TITLE
cap production deploy reports problems tracking statistics

### ISSUE THREAD

**Issue by scottb** [capistrano/stats#42]
On most (but not all) of my deploys, whether successful or not, I get a message from Capistrano saying "There was a problem tracking statistics, please report to https://github.com/capistrano/stats". Since it doesn't seem to have any other logging or debug info, I've no idea what would be useful to report here, other than that it's not a transient thing.

**Comment by leehambley** [comment]
Simply upgrade, and/or remove `capistrano-stats` from your `Gemfile` if it is there. For a short period around the end of 2014 we ran opt-in analytics in Capistrano to gather feedback about which platforms it was mostly used on. The stats server, and the gem haven't been required for about 6 months :) Feel free just to drop it.
